//! Randomized differential tester: the same generated SQL program runs
//! against **mpedb**, against **/usr/bin/sqlite3** (a STRICT table, whose
//! rigid typing matches mpedb's), and — in the three-way mode — against a
//! throwaway **PostgreSQL 16** cluster ([`crate::pg::PgCluster`]).
//! Per-statement outcomes plus every SELECT's output are compared across
//! all engines. Any divergence is minimized (greedy statement removal,
//! re-checking every engine each step) and reported as a self-contained
//! reproduction.
//!
//! # Fixed schema
//!
//! mpedb (TOML):  `t(pk int64 PRIMARY KEY, a int64, b float64, c text)`
//! sqlite:        `CREATE TABLE t (pk INTEGER PRIMARY KEY, a INT, b REAL,
//!                 c TEXT) STRICT;`
//! postgres:      `CREATE TABLE t (pk bigint PRIMARY KEY, a bigint,
//!                 b double precision, c text);`
//!
//! # Known semantic differences — normalized or avoided in generation
//!
//! Each of these would produce false-positive divergences; the generator or
//! comparator handles them explicitly:
//!
//! 1. **Float formatting.** sqlite prints REAL with `%!.15g`-style text;
//!    mpedb returns f64 directly. The comparator parses sqlite's text and
//!    compares numerically with tolerance (and generated float literals are
//!    multiples of 0.25, exactly representable, so arithmetic stays exact).
//! 2. **Text collation.** mpedb compares text bytewise (binary collation);
//!    sqlite's default BINARY collation matches — but only because the
//!    generator emits pure ASCII (lowercase letters). Case differences would
//!    also hit sqlite's ASCII-case-insensitive `LIKE`, so all generated text
//!    and LIKE patterns are lowercase-only.
//! 3. **`INTEGER PRIMARY KEY` rowid aliasing.** sqlite treats `pk` as the
//!    rowid. Same lookup/uniqueness semantics for this schema, EXCEPT that
//!    inserting NULL into it auto-assigns a rowid where mpedb raises
//!    NOT NULL — so the generator never writes NULL (or omits) `pk`.
//! 4. **Division/modulo.** sqlite yields NULL on division by zero; mpedb
//!    raises an error (and PostgreSQL raises a different error). `/` and
//!    `%` are never generated.
//! 5. **Constraint errors.** PK/UNIQUE/NOT-NULL failures compare only as
//!    "all engines failed", never by message. Every engine rolls back the
//!    whole failed statement (sqlite: statement-level ABORT; mpedb:
//!    autocommit transaction abort; postgres: statement-level rollback in
//!    autocommit), so state stays in sync.
//! 6. **Integer overflow.** mpedb errors, sqlite wraps to REAL, postgres
//!    errors. Generated literals and self-referential updates keep |values|
//!    far below i64 range, so overflow is unreachable.
//!
//! # PostgreSQL-specific differences (three-way mode)
//!
//! 7. **Float output text.** `double precision` prints shortest-exact
//!    decimal (`extra_float_digits=1` default since PG 12), and an integer
//!    assigned into `b` prints without a decimal point (`10`, not `10.0`).
//!    Already absorbed by difference #1's numeric comparison — psql rows
//!    are parsed with the same `parse_pipe_row` as sqlite's.
//! 8. **`ORDER BY` NULLS placement.** PostgreSQL defaults to NULLS LAST in
//!    ASC (and NULLS FIRST in DESC); mpedb and sqlite do the opposite. Moot
//!    here by construction: the generator only ever orders by `pk`, which
//!    is NOT NULL — pinned by the `generator_only_orders_by_pk` unit test
//!    so a generator change cannot silently re-open this hole.
//! 9. **No STRICT needed.** PostgreSQL is rigidly typed already — closer to
//!    mpedb than sqlite is. The plain `CREATE TABLE` above needs no
//!    equivalent of sqlite's `STRICT` marker; type-correct-by-construction
//!    generation (see [`gen_pred`]) keeps the remaining coercion corners
//!    (e.g. `bigint` → `double precision` on `SET b = a`) identical.
//! 10. **LIKE case sensitivity.** PostgreSQL's `LIKE` is case-sensitive,
//!     exactly like mpedb's. The lowercase-only rule from difference #2
//!     stays purely for sqlite's ASCII-case-insensitive `LIKE`.
//! 11. **Empty string vs NULL.** PostgreSQL keeps `''` and NULL distinct,
//!     like mpedb (and sqlite; Oracle is the odd one out). The generator
//!     deliberately emits `''` text literals (values and predicate
//!     comparands) so this is *exercised*, not just assumed — pinned by the
//!     `generator_covers_empty_string` unit test. In psql output the empty
//!     field is unambiguous because NULL prints as the `NULL` sentinel
//!     (`-P null=NULL`, same convention as sqlite's `.nullvalue NULL`).
//!
//! Determinism: programs are generated by a seeded xorshift
//! ([`crate::Xorshift`]); a failure report includes the seed, and the
//! minimized program reproduces it standalone.

use crate::pg::{PgCluster, PG_UNAVAILABLE};
use crate::{Failure, Result, TempDir, Xorshift};
use mpedb::{Config, Database, ExecResult, Value};
use std::collections::HashMap;
use std::fmt::Write as _;
use std::io::Write as _;
use std::path::Path;
use std::process::{Command, Stdio};

const SQLITE3: &str = "/usr/bin/sqlite3";

const MPEDB_SCHEMA: &str = r#"
[[table]]
name = "t"
primary_key = ["pk"]

  [[table.column]]
  name = "pk"
  type = "int64"

  [[table.column]]
  name = "a"
  type = "int64"

  [[table.column]]
  name = "b"
  type = "float64"

  [[table.column]]
  name = "c"
  type = "text"
"#;

const SQLITE_SCHEMA: &str = "CREATE TABLE t (pk INTEGER PRIMARY KEY, a INT, b REAL, c TEXT) STRICT;";

const PG_SCHEMA: &str =
    "CREATE TABLE t (pk bigint PRIMARY KEY, a bigint, b double precision, c text);";

/// One generated statement. `is_select` decides whether row output is
/// compared (SELECTs) or only the success/failure status (DML).
#[derive(Clone, Debug)]
pub struct GenStmt {
    pub sql: String,
    pub is_select: bool,
    /// The column types this SELECT returns, in order. sqlite3 and psql both
    /// hand back untyped pipe-separated TEXT, so the shape is what tells the
    /// parser whether `650` is the integer 650 or the text "650" — mpedb
    /// returns typed values and would otherwise compare unequal to both.
    /// Empty for non-SELECTs.
    pub shape: Vec<Kind>,
}

/// The type of one output column, for parsing the text engines' rows back.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Kind {
    Int,
    Float,
    Text,
}

/// The shape of the base probe `SELECT pk, a, b, c FROM t`.
const BASE_SHAPE: [Kind; 4] = [Kind::Int, Kind::Int, Kind::Float, Kind::Text];

/// Aggregate results of a differential run.
#[derive(Debug, Default, Clone, Copy)]
pub struct DiffStats {
    pub programs: usize,
    pub statements: usize,
    pub selects_compared: usize,
    /// Statements that failed in BOTH engines (constraint violations the
    /// generator provokes deliberately; counted to show the corpus actually
    /// exercises error paths).
    pub agreed_failures: usize,
}

/// Result of a three-way run: either it ran, or the environment cannot run
/// PostgreSQL (no root here; e.g. `initdb` missing). Callers should treat
/// [`PgDiff::Unavailable`] as a LOUD skip, never as a pass.
#[derive(Debug)]
pub enum PgDiff {
    Ran(DiffStats),
    Unavailable(String),
}

/// Run `programs` random programs of `stmts_per_program` statements each,
/// starting from `base_seed` (program k uses seed `base_seed + k`), against
/// mpedb and sqlite3. Returns stats, or a [`Failure`] carrying the seed and
/// the **minimized** diverging program.
pub fn run_differential(
    base_seed: u64,
    programs: usize,
    stmts_per_program: usize,
) -> Result<DiffStats> {
    run_differential_impl(base_seed, programs, stmts_per_program, None)
}

/// Three-way differential: mpedb vs sqlite3 vs PostgreSQL 16, one throwaway
/// cluster for the whole run (each program still gets a fresh `t`). Every
/// statement must agree in all three engines. Fails soft when the
/// environment cannot start PostgreSQL (see [`PgDiff::Unavailable`]).
pub fn run_differential_3way(
    base_seed: u64,
    programs: usize,
    stmts_per_program: usize,
) -> Result<PgDiff> {
    let cluster = match PgCluster::start() {
        Ok(c) => c,
        Err(Failure(msg)) if msg.starts_with(PG_UNAVAILABLE) => {
            return Ok(PgDiff::Unavailable(msg));
        }
        Err(e) => return Err(e),
    };
    run_differential_impl(base_seed, programs, stmts_per_program, Some(&cluster))
        .map(PgDiff::Ran)
}

fn run_differential_impl(
    base_seed: u64,
    programs: usize,
    stmts_per_program: usize,
    pg: Option<&PgCluster>,
) -> Result<DiffStats> {
    if !Path::new(SQLITE3).exists() {
        return Err(Failure(format!("{SQLITE3} not found")));
    }
    let mut stats = DiffStats::default();
    for k in 0..programs {
        let seed = base_seed + k as u64;
        let program = generate_program(seed, stmts_per_program);
        match check_program(&program, pg)? {
            Agreement::Agree {
                statements,
                selects,
                agreed_failures,
            } => {
                stats.programs += 1;
                stats.statements += statements;
                stats.selects_compared += selects;
                stats.agreed_failures += agreed_failures;
            }
            Agreement::Diverge(first_msg) => {
                let minimal = minimize(&program, pg)?;
                let detail = match check_program(&minimal, pg)? {
                    Agreement::Diverge(m) => m,
                    // Non-deterministic environment failure; report the
                    // original divergence.
                    Agreement::Agree { .. } => first_msg,
                };
                let engines = if pg.is_some() {
                    "mpedb/sqlite3/postgres"
                } else {
                    "mpedb/sqlite3"
                };
                let mut report = String::new();
                let _ = writeln!(
                    report,
                    "DIVERGENCE between {engines} (seed {seed}, program {k})"
                );
                let _ = writeln!(report, "{detail}");
                let _ = writeln!(
                    report,
                    "minimal program ({} statements):",
                    minimal.len()
                );
                for s in &minimal {
                    let _ = writeln!(report, "  {};", s.sql);
                }
                return Err(Failure(report));
            }
        }
    }
    Ok(stats)
}

// ---------------------------------------------------------------- outcomes

/// Per-statement outcome, normalized across engines. Row values for SELECTs
/// are kept engine-native and compared by [`values_equal`].
enum Outcome {
    Ok,
    /// SELECT rows (engine-native values; mpedb: `Value`, sqlite: text).
    Rows(Vec<Vec<Field>>),
    Failed,
}

/// A single normalized field.
#[derive(Debug, Clone, PartialEq)]
enum Field {
    Null,
    Int(i64),
    Float(f64),
    Text(String),
}

impl std::fmt::Display for Field {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Field::Null => f.write_str("NULL"),
            Field::Int(v) => write!(f, "{v}"),
            // %.3f both sides (module docs, difference #1)
            Field::Float(v) => write!(f, "{v:.3}"),
            Field::Text(s) => f.write_str(s),
        }
    }
}

/// Tolerant float comparison (difference #1 in the module docs). Generated
/// arithmetic is exact in binary, so this tolerance only absorbs the text
/// round-trip through sqlite's output formatting.
fn fields_equal(a: &Field, b: &Field) -> bool {
    match (a, b) {
        (Field::Float(x), Field::Float(y)) => {
            (x - y).abs() <= 1e-9 * x.abs().max(y.abs()).max(1.0)
        }
        _ => a == b,
    }
}

enum Agreement {
    Agree {
        statements: usize,
        selects: usize,
        agreed_failures: usize,
    },
    Diverge(String),
}

/// Run one program against mpedb, sqlite3 and (when `pg` is given)
/// PostgreSQL, and compare per statement. mpedb is the comparison anchor:
/// every other engine is checked against it, which makes all engines
/// pairwise-equal on agreement.
fn check_program(program: &[GenStmt], pg: Option<&PgCluster>) -> Result<Agreement> {
    let mp = run_mpedb(program)?;
    let sq = run_sqlite(program)?;
    let pgv = match pg {
        Some(cluster) => Some(run_pg(program, cluster)?),
        None => None,
    };
    debug_assert_eq!(mp.len(), program.len());
    debug_assert_eq!(sq.len(), program.len());

    let mut selects = 0;
    let mut agreed_failures = 0;
    for (i, stmt) in program.iter().enumerate() {
        // (engine name, outcome) for every engine in this run.
        let mut outs: Vec<(&'static str, &Outcome)> =
            vec![("mpedb", &mp[i]), ("sqlite3", &sq[i])];
        if let Some(p) = &pgv {
            outs.push(("postgres", &p[i]));
        }

        // Success/failure status must be unanimous (difference #5: failures
        // compare only as "all failed", never by message).
        let n_failed = outs
            .iter()
            .filter(|(_, o)| matches!(o, Outcome::Failed))
            .count();
        if n_failed == outs.len() {
            agreed_failures += 1;
            continue;
        }
        if n_failed > 0 {
            let status = outs
                .iter()
                .map(|(name, o)| {
                    let s = if matches!(o, Outcome::Failed) {
                        "FAILED"
                    } else {
                        "ok"
                    };
                    format!("{name}={s}")
                })
                .collect::<Vec<_>>()
                .join(", ");
            return Ok(Agreement::Diverge(format!(
                "statement {i} status differs: {status}\n  sql: {}",
                stmt.sql
            )));
        }

        // All succeeded: SELECT row output must match mpedb's everywhere.
        match &mp[i] {
            Outcome::Rows(m) => {
                selects += 1;
                for (name, o) in &outs[1..] {
                    let Outcome::Rows(theirs) = o else {
                        return Ok(Agreement::Diverge(format!(
                            "statement {i}: result shape differs (mpedb rows vs {name} non-rows)\n  sql: {}",
                            stmt.sql
                        )));
                    };
                    if let Some(msg) = compare_rows(m, theirs, name) {
                        return Ok(Agreement::Diverge(format!(
                            "statement {i} SELECT output differs (mpedb vs {name})\n  sql: {}\n{msg}",
                            stmt.sql
                        )));
                    }
                }
            }
            Outcome::Ok => {
                if let Some((name, _)) = outs[1..]
                    .iter()
                    .find(|(_, o)| !matches!(o, Outcome::Ok))
                {
                    return Ok(Agreement::Diverge(format!(
                        "statement {i}: result shape differs (mpedb ok vs {name} rows)\n  sql: {}",
                        stmt.sql
                    )));
                }
            }
            Outcome::Failed => unreachable!("n_failed == 0 checked above"),
        }
    }
    Ok(Agreement::Agree {
        statements: program.len(),
        selects,
        agreed_failures,
    })
}

fn compare_rows(m: &[Vec<Field>], s: &[Vec<Field>], other_name: &str) -> Option<String> {
    let render = |rows: &[Vec<Field>]| -> String {
        rows.iter()
            .map(|r| {
                r.iter()
                    .map(|f| f.to_string())
                    .collect::<Vec<_>>()
                    .join("|")
            })
            .collect::<Vec<_>>()
            .join("\n    ")
    };
    let equal = m.len() == s.len()
        && m.iter()
            .zip(s)
            .all(|(rm, rs)| {
                rm.len() == rs.len() && rm.iter().zip(rs).all(|(a, b)| fields_equal(a, b))
            });
    if equal {
        None
    } else {
        Some(format!(
            "  mpedb rows ({}):\n    {}\n  {other_name} rows ({}):\n    {}",
            m.len(),
            render(m),
            s.len(),
            render(s)
        ))
    }
}

// ---------------------------------------------------------------- mpedb side

fn run_mpedb(program: &[GenStmt]) -> Result<Vec<Outcome>> {
    let dir = TempDir::new("diff")?;
    let toml = format!(
        "[database]\npath = \"{}\"\nsize_mb = 16\nmax_readers = 8\n{}",
        dir.db_path("diff").display(),
        MPEDB_SCHEMA
    );
    let config = Config::from_toml_str(&toml)
        .map_err(|e| Failure(format!("differential schema rejected: {e}")))?;
    let db = Database::open_with_config(config)
        .map_err(|e| Failure(format!("mpedb open failed: {e}")))?;

    let mut out = Vec::with_capacity(program.len());
    for stmt in program {
        out.push(match db.query(&stmt.sql, &[]) {
            Ok(ExecResult::Rows { rows, .. }) => {
                let mut frows = Vec::with_capacity(rows.len());
                for row in rows {
                    frows.push(
                        row.into_iter()
                            .map(|v| match v {
                                Value::Null => Field::Null,
                                Value::Int(x) => Field::Int(x),
                                Value::Float(x) => Field::Float(x),
                                Value::Text(s) => Field::Text(s),
                                other => Field::Text(format!("<unexpected {other:?}>")),
                            })
                            .collect(),
                    );
                }
                Outcome::Rows(frows)
            }
            Ok(_) => Outcome::Ok,
            Err(_) => Outcome::Failed,
        });
    }
    db.verify()
        .map_err(|e| Failure(format!("mpedb verify failed after program: {e}")))?;
    Ok(out)
}

// ---------------------------------------------------------------- sqlite side

/// Run the program in one sqlite3 batch process. Each statement occupies
/// exactly one script line, bracketed by `SELECT '@S<i>';` markers, so
/// stdout sections map to statements and stderr's `... near line N:` errors
/// map back through the line number.
fn run_sqlite(program: &[GenStmt]) -> Result<Vec<Outcome>> {
    let dir = TempDir::new("sqlite")?;
    let db_path = dir.path().join("diff.sqlite3");

    let mut script = String::new();
    let mut line_of_stmt: HashMap<usize, usize> = HashMap::new(); // line -> stmt idx
    let mut lineno = 0usize;
    let mut push_line = |script: &mut String, l: &str| {
        script.push_str(l);
        script.push('\n');
        lineno += 1;
        lineno
    };
    push_line(&mut script, ".mode list");
    push_line(&mut script, ".nullvalue NULL");
    push_line(&mut script, SQLITE_SCHEMA);
    for (i, stmt) in program.iter().enumerate() {
        push_line(&mut script, &format!("SELECT '@S{i}';"));
        debug_assert!(!stmt.sql.contains('\n'), "one line per statement");
        let ln = push_line(&mut script, &format!("{};", stmt.sql));
        line_of_stmt.insert(ln, i);
    }
    push_line(&mut script, "SELECT '@SEND';");

    let mut child = Command::new(SQLITE3)
        .arg(&db_path)
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .map_err(|e| Failure(format!("failed to spawn {SQLITE3}: {e}")))?;
    child
        .stdin
        .as_mut()
        .expect("piped stdin")
        .write_all(script.as_bytes())?;
    let output = child.wait_with_output()?;
    let stdout = String::from_utf8_lossy(&output.stdout);
    let stderr = String::from_utf8_lossy(&output.stderr);

    // stderr: `Runtime error near line N: ...` / `Parse error near line N: ...`
    let mut failed = vec![false; program.len()];
    for line in stderr.lines() {
        let Some(rest) = line.split("near line ").nth(1) else {
            if line.trim().is_empty() {
                continue;
            }
            return Err(Failure(format!(
                "unrecognized sqlite3 stderr line: {line}\nscript:\n{script}"
            )));
        };
        let n: usize = rest
            .split(':')
            .next()
            .and_then(|s| s.trim().parse().ok())
            .ok_or_else(|| Failure(format!("cannot parse sqlite3 error line: {line}")))?;
        let idx = *line_of_stmt.get(&n).ok_or_else(|| {
            Failure(format!(
                "sqlite3 error on unexpected script line {n}: {line}"
            ))
        })?;
        failed[idx] = true;
    }

    // stdout: marker-delimited sections.
    let mut sections: Vec<Vec<&str>> = vec![Vec::new(); program.len()];
    let mut current: Option<usize> = None;
    let mut saw_end = false;
    for line in stdout.lines() {
        if let Some(idx) = line.strip_prefix("@S") {
            if idx == "END" {
                saw_end = true;
                current = None;
                continue;
            }
            if let Ok(i) = idx.parse::<usize>() {
                if i < program.len() {
                    current = Some(i);
                    continue;
                }
            }
        }
        if let Some(i) = current {
            sections[i].push(line);
        }
        // Output before the first marker (CREATE TABLE) would be a harness
        // bug; there is none, so silently ignoring is fine.
    }
    if !saw_end {
        return Err(Failure(format!(
            "sqlite3 output truncated (no @SEND marker)\nstderr: {stderr}"
        )));
    }

    let mut out = Vec::with_capacity(program.len());
    for (i, stmt) in program.iter().enumerate() {
        if failed[i] {
            out.push(Outcome::Failed);
        } else if stmt.is_select {
            let mut rows = Vec::with_capacity(sections[i].len());
            for line in &sections[i] {
                rows.push(parse_pipe_row(line, &stmt.shape)?);
            }
            out.push(Outcome::Rows(rows));
        } else {
            out.push(Outcome::Ok);
        }
    }
    Ok(out)
}

// ------------------------------------------------------------- postgres side

/// Run the program in one `psql` batch against the throwaway cluster.
///
/// Statement status uses psql's `:ERROR` variable (true iff the last SQL
/// statement failed): every statement is followed by
/// `\if :ERROR \echo @E<i> \else \echo @K<i> \endif`, so each statement
/// deterministically emits exactly one status marker — sturdier than
/// inferring failure from a *missing* marker, and it never needs stderr
/// (which psql emits without usable line mapping). `ON_ERROR_STOP` stays
/// off so a failed statement — an *expected* event, the generator provokes
/// constraint violations constantly — rolls back alone (autocommit
/// statement-level rollback, difference #5) and the batch continues.
///
/// stdout layout per statement: `@S<i>` (via `\echo`), then the SELECT's
/// rows if any (tuples-only, `|`-separated, `NULL` sentinel — the exact
/// shape [`parse_pipe_row`] handles for sqlite), then `@K<i>` or `@E<i>`.
/// Marker lines cannot collide with row lines: rows of the fixed 4-column
/// SELECT always contain `|`, and generated text is lowercase-only.
fn run_pg(program: &[GenStmt], cluster: &PgCluster) -> Result<Vec<Outcome>> {
    let mut script = String::new();
    script.push_str("DROP TABLE IF EXISTS t;\n");
    script.push_str(PG_SCHEMA);
    script.push('\n');
    script.push_str("\\if :ERROR\n\\echo @SETUPFAIL\n\\endif\n");
    for (i, stmt) in program.iter().enumerate() {
        debug_assert!(!stmt.sql.contains('\n'), "one line per statement");
        let _ = writeln!(
            script,
            "\\echo @S{i}\n{};\n\\if :ERROR\n\\echo @E{i}\n\\else\n\\echo @K{i}\n\\endif",
            stmt.sql
        );
    }
    script.push_str("\\echo @SEND\n");

    let mut child = cluster
        .psql()
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .map_err(|e| Failure(format!("{PG_UNAVAILABLE}failed to spawn psql: {e}")))?;
    child
        .stdin
        .as_mut()
        .expect("piped stdin")
        .write_all(script.as_bytes())?;
    let output = child.wait_with_output()?;
    let stdout = String::from_utf8_lossy(&output.stdout);
    let stderr = String::from_utf8_lossy(&output.stderr);
    if !output.status.success() {
        return Err(Failure(format!(
            "psql exited with {}\nstderr: {stderr}",
            output.status
        )));
    }

    // stderr is deliberately not parsed: expected errors are detected via
    // :ERROR markers, and NOTICEs (e.g. from DROP TABLE IF EXISTS) are noise.
    let mut failed = vec![false; program.len()];
    let mut sections: Vec<Vec<&str>> = vec![Vec::new(); program.len()];
    let mut status_seen = vec![false; program.len()];
    let mut current: Option<usize> = None;
    let mut saw_end = false;
    for line in stdout.lines() {
        if line == "@SETUPFAIL" {
            return Err(Failure(format!(
                "postgres CREATE TABLE failed\nstderr: {stderr}"
            )));
        }
        if line == "@SEND" {
            saw_end = true;
            current = None;
            continue;
        }
        let marker = |prefix: &str| -> Option<usize> {
            line.strip_prefix(prefix)?
                .parse::<usize>()
                .ok()
                .filter(|&i| i < program.len())
        };
        if let Some(i) = marker("@S") {
            current = Some(i);
            continue;
        }
        if let Some(i) = marker("@K") {
            status_seen[i] = true;
            current = None;
            continue;
        }
        if let Some(i) = marker("@E") {
            failed[i] = true;
            status_seen[i] = true;
            current = None;
            continue;
        }
        if let Some(i) = current {
            sections[i].push(line);
        }
    }
    if !saw_end || status_seen.iter().any(|&s| !s) {
        return Err(Failure(format!(
            "psql output truncated (missing @SEND or a status marker)\n\
             stdout:\n{stdout}\nstderr: {stderr}"
        )));
    }

    let mut out = Vec::with_capacity(program.len());
    for (i, stmt) in program.iter().enumerate() {
        if failed[i] {
            out.push(Outcome::Failed);
        } else if stmt.is_select {
            let mut rows = Vec::with_capacity(sections[i].len());
            for line in &sections[i] {
                rows.push(parse_pipe_row(line, &stmt.shape)?);
            }
            out.push(Outcome::Rows(rows));
        } else {
            out.push(Outcome::Ok);
        }
    }
    Ok(out)
}

/// Parse one pipe-separated output row against the statement's declared
/// `shape` — the shared wire format of sqlite3's `.mode list` and psql's
/// unaligned tuples-only mode. Generated text never contains `|` or the
/// literal string `NULL`, so the split and the NULL sentinel are unambiguous
/// (an empty text field is `''`, distinct from the sentinel — difference
/// #11).
///
/// The shape is per-statement rather than fixed because aggregates return
/// whatever they return: `count(*)` is an integer where the column under it
/// is text, and `avg(a)` is a float where `a` is an integer.
fn parse_pipe_row(line: &str, shape: &[Kind]) -> Result<Vec<Field>> {
    let parts: Vec<&str> = line.split('|').collect();
    if parts.len() != shape.len() {
        return Err(Failure(format!(
            "row has {} fields, expected {}: {line}",
            parts.len(),
            shape.len()
        )));
    }
    let mut out = Vec::with_capacity(shape.len());
    for (part, kind) in parts.iter().zip(shape) {
        out.push(match (kind, *part) {
            (_, "NULL") => Field::Null,
            (Kind::Int, s) => s
                .parse::<i64>()
                .map(Field::Int)
                .map_err(|_| Failure(format!("cannot parse int field `{s}` in row: {line}")))?,
            // PG returns `sum(bigint)` and `avg(bigint)` as NUMERIC, printed
            // with a decimal point and full scale ("162.5000000000000000");
            // sqlite and mpedb use f64. Parsing both as f64 and comparing with
            // difference #1's tolerance is what makes those agree.
            (Kind::Float, s) => s
                .parse::<f64>()
                .map(Field::Float)
                .map_err(|_| Failure(format!("cannot parse float field `{s}` in row: {line}")))?,
            (Kind::Text, s) => Field::Text(s.to_string()),
        });
    }
    Ok(out)
}

// ---------------------------------------------------------------- minimizer

/// Greedy delta-minimization: repeatedly try dropping one statement; keep
/// the removal if the program still diverges (in the same engine set that
/// found it). Quadratic in program length, but only runs on failure.
fn minimize(program: &[GenStmt], pg: Option<&PgCluster>) -> Result<Vec<GenStmt>> {
    let mut best: Vec<GenStmt> = program.to_vec();
    loop {
        let mut shrunk = false;
        let mut i = 0;
        while i < best.len() {
            let mut candidate = best.clone();
            candidate.remove(i);
            if candidate.is_empty() {
                break;
            }
            if matches!(check_program(&candidate, pg)?, Agreement::Diverge(_)) {
                best = candidate;
                shrunk = true;
                // re-test the same index (now the next statement)
            } else {
                i += 1;
            }
        }
        if !shrunk {
            return Ok(best);
        }
    }
}

// ---------------------------------------------------------------- generator

/// Generate one program: INSERT/UPDATE/DELETE with literal values,
/// interleaved with `SELECT ... ORDER BY pk` probes, ending with a full-table
/// probe. All the "known differences" rules from the module docs are
/// enforced here.
pub fn generate_program(seed: u64, n_stmts: usize) -> Vec<GenStmt> {
    let mut rng = Xorshift::new(seed);
    let mut out = Vec::with_capacity(n_stmts + 1);
    for _ in 0..n_stmts.saturating_sub(1) {
        let stmt = match rng.below(100) {
            0..=39 => gen_insert(&mut rng),
            40..=59 => gen_update(&mut rng),
            60..=74 => gen_delete(&mut rng),
            75..=84 => gen_select(&mut rng),
            85..=94 => gen_agg_select(&mut rng),
            _ => gen_distinct_select(&mut rng),
        };
        out.push(stmt);
    }
    out.push(GenStmt {
        sql: "SELECT pk, a, b, c FROM t ORDER BY pk".into(),
        is_select: true,
        shape: BASE_SHAPE.to_vec(),
    });
    out
}

/// pk domain is small so PK collisions (agreed constraint failures) and
/// non-empty range scans happen constantly.
fn gen_pk(rng: &mut Xorshift) -> i64 {
    rng.range_i64(0, 47)
}

/// int64 column `a`: NULL 1-in-5, else small (difference #6: no overflow).
fn gen_a(rng: &mut Xorshift) -> String {
    if rng.chance(1, 5) {
        "NULL".into()
    } else {
        rng.range_i64(-100, 100).to_string()
    }
}

/// float64 column `b`: NULL 1-in-5, else a multiple of 0.25 rendered with
/// two decimals — exactly representable in binary, so arithmetic and
/// comparisons agree bit-for-bit across engines (difference #1).
fn gen_b(rng: &mut Xorshift) -> String {
    if rng.chance(1, 5) {
        "NULL".into()
    } else {
        format!("{:.2}", rng.range_i64(-100, 100) as f64 * 0.25)
    }
}

/// text column `c`: NULL 1-in-5, the EMPTY string `''` 1-in-8 of the rest
/// (difference #11: `''` and NULL must stay distinct in all engines, in
/// values and in predicates via [`gen_c_nonnull`]), else 1-6 lowercase
/// ASCII letters (difference #2: ASCII-only, lowercase-only; never `|`,
/// never the literal string `NULL`, never `%`/`_` — the engine's known
/// LIKE bug corpus lives in `tests/engine_bugs.rs`, not here).
fn gen_c(rng: &mut Xorshift) -> String {
    if rng.chance(1, 5) {
        return "NULL".into();
    }
    if rng.chance(1, 8) {
        return "''".into();
    }
    let n = rng.range_i64(1, 6) as usize;
    let mut s = String::with_capacity(n + 2);
    s.push('\'');
    for _ in 0..n {
        s.push((b'a' + rng.below(26) as u8) as char);
    }
    s.push('\'');
    s
}

fn gen_insert(rng: &mut Xorshift) -> GenStmt {
    let n_rows = 1 + rng.below(3);
    let mut rows = Vec::with_capacity(n_rows as usize);
    // Sometimes omit trailing columns (both engines default omitted nullable
    // columns to NULL). `pk` is always present (difference #3).
    let cols: &str = match rng.below(10) {
        0 => "pk, a",
        1 => "pk, c",
        _ => "pk, a, b, c",
    };
    for _ in 0..n_rows {
        let row = match cols {
            "pk, a" => format!("({}, {})", gen_pk(rng), gen_a(rng)),
            "pk, c" => format!("({}, {})", gen_pk(rng), gen_c(rng)),
            _ => format!(
                "({}, {}, {}, {})",
                gen_pk(rng),
                gen_a(rng),
                gen_b(rng),
                gen_c(rng)
            ),
        };
        rows.push(row);
    }
    GenStmt {
        sql: format!("INSERT INTO t ({cols}) VALUES {}", rows.join(", ")),
        is_select: false,
        shape: Vec::new(),
    }
}

fn gen_update(rng: &mut Xorshift) -> GenStmt {
    let mut sets = Vec::new();
    // One or two SET clauses over distinct non-PK columns (mpedb rejects SET
    // on PK columns, and multi-row pk updates would be order-dependent).
    let first = rng.below(3);
    let second = if rng.chance(1, 3) {
        Some((first + 1 + rng.below(2)) % 3)
    } else {
        None
    };
    for col in std::iter::once(first).chain(second) {
        sets.push(match col {
            0 => match rng.below(3) {
                // Self-referential SET evaluates against the OLD row in both
                // engines.
                0 => format!("a = a + {}", rng.range_i64(-3, 3)),
                1 => format!("a = {}", gen_a(rng)),
                _ => "a = NULL".into(),
            },
            1 => match rng.below(4) {
                0 => "b = b + 0.25".into(),
                1 => format!("b = {}", gen_b(rng)),
                // Cross-column int->float assignment: both engines coerce
                // INT into a REAL/float64 column.
                2 => "b = a".into(),
                _ => "b = NULL".into(),
            },
            _ => match rng.below(3) {
                0 => format!("c = {}", gen_c(rng)),
                _ => "c = NULL".into(),
            },
        });
    }
    let where_clause = if rng.chance(9, 10) {
        format!(" WHERE {}", gen_pred(rng))
    } else {
        String::new()
    };
    GenStmt {
        sql: format!("UPDATE t SET {}{}", sets.join(", "), where_clause),
        is_select: false,
        shape: Vec::new(),
    }
}

fn gen_delete(rng: &mut Xorshift) -> GenStmt {
    let where_clause = if rng.chance(9, 10) {
        format!(" WHERE {}", gen_pred(rng))
    } else {
        String::new() // occasional full-table delete
    };
    GenStmt {
        sql: format!("DELETE FROM t{where_clause}"),
        is_select: false,
        shape: Vec::new(),
    }
}

fn gen_select(rng: &mut Xorshift) -> GenStmt {
    let where_clause = if rng.chance(3, 4) {
        format!(" WHERE {}", gen_pred(rng))
    } else {
        String::new()
    };
    // ORDER BY pk keeps output deterministic in every engine; pk is NOT
    // NULL so NULL-ordering conventions (mpedb/sqlite: NULLS FIRST asc;
    // postgres: NULLS LAST asc — difference #8) never come into play. Only
    // ever order by pk; `generator_only_orders_by_pk` pins this.
    let dir = if rng.chance(1, 4) { " DESC" } else { "" };
    let limit = if rng.chance(1, 5) {
        let mut l = format!(" LIMIT {}", rng.below(20));
        if rng.chance(1, 2) {
            let _ = write!(l, " OFFSET {}", rng.below(10));
        }
        l
    } else {
        String::new()
    };
    GenStmt {
        sql: format!("SELECT pk, a, b, c FROM t{where_clause} ORDER BY pk{dir}{limit}"),
        is_select: true,
        shape: BASE_SHAPE.to_vec(),
    }
}

/// Aggregate probes: `count/sum/avg/min/max`, with and without GROUP BY and
/// HAVING, compared three-way against sqlite3 and PostgreSQL.
///
/// Two constraints shape what may be generated here, and both are the same
/// rule seen twice: **the output order must be forced, and never by anything
/// nullable.**
///
///   Any GROUP BY needs an ORDER BY, because group order is an engine's
///   choice — mpedb emits keycode order, sqlite follows its scan, PG may
///   hash. Without one, three correct engines disagree.
///
///   That ORDER BY cannot land on a nullable column, or difference #8 (PG
///   sorts NULLS LAST ascending, mpedb and sqlite FIRST) fires. So every
///   grouped probe guards its key with `IS NOT NULL`, which is what
///   `generator_only_orders_by_non_null` checks for. The NULL group itself
///   is not lost — `aggregates.test` pins it against sqlite directly.
///
/// What is safe here and why: `a` is bounded to ±100 over ≤48 rows, so
/// `sum(a)` cannot overflow (difference #6). `b` is a multiple of 0.25 with
/// |b| ≤ 25, so a sum of ≤48 of them is exact in binary REGARDLESS of
/// summation order (difference #1) — otherwise engines adding in different
/// row orders would drift apart and nothing would be provable. `min/max` on
/// text is order-independent, and the test cluster runs `--locale=C`, so it
/// collates bytewise like mpedb and sqlite (difference #2).
fn gen_agg_select(rng: &mut Xorshift) -> GenStmt {
    let where_clause = |rng: &mut Xorshift| {
        if rng.chance(1, 2) {
            format!(" WHERE {}", gen_pred(rng))
        } else {
            String::new()
        }
    };
    match rng.below(6) {
        // Bare aggregates: always exactly ONE row, even over an empty table —
        // and that row is `0|NULL|NULL|NULL` there, which is the split this
        // probe exists to check three-way.
        0 => GenStmt {
            sql: format!(
                "SELECT count(*), count(a), sum(a), min(a) FROM t{}",
                where_clause(rng)
            ),
            is_select: true,
            shape: vec![Kind::Int, Kind::Int, Kind::Int, Kind::Int],
        },
        1 => GenStmt {
            sql: format!(
                "SELECT count(*), sum(b), min(b), max(b) FROM t{}",
                where_clause(rng)
            ),
            is_select: true,
            shape: vec![Kind::Int, Kind::Float, Kind::Float, Kind::Float],
        },
        // avg over an integer column: PG returns NUMERIC, the others f64.
        2 => GenStmt {
            sql: format!("SELECT avg(a), avg(b) FROM t{}", where_clause(rng)),
            is_select: true,
            shape: vec![Kind::Float, Kind::Float],
        },
        3 => GenStmt {
            sql: format!("SELECT min(c), max(c), count(c) FROM t{}", where_clause(rng)),
            is_select: true,
            shape: vec![Kind::Text, Kind::Text, Kind::Int],
        },
        // Grouped, on the int key.
        4 => {
            let having = if rng.chance(1, 3) {
                format!(" HAVING count(*) > {}", rng.below(3))
            } else {
                String::new()
            };
            GenStmt {
                sql: format!(
                    "SELECT a, count(*), sum(b) FROM t WHERE a IS NOT NULL GROUP BY a{having} \
                     ORDER BY a"
                ),
                is_select: true,
                shape: vec![Kind::Int, Kind::Int, Kind::Float],
            }
        }
        // Grouped, on the text key.
        _ => {
            let having = if rng.chance(1, 3) {
                format!(" HAVING sum(a) > {}", rng.range_i64(-20, 20))
            } else {
                String::new()
            };
            GenStmt {
                sql: format!(
                    "SELECT c, count(*), sum(a), min(a) FROM t WHERE c IS NOT NULL GROUP BY \
                     c{having} ORDER BY c"
                ),
                is_select: true,
                shape: vec![Kind::Text, Kind::Int, Kind::Int, Kind::Int],
            }
        }
    }
}

/// `SELECT DISTINCT` probes.
///
/// Every key is in the SELECT list and every sort key is NULL-free, for the
/// same two reasons `gen_agg_select` documents: without an ORDER BY the output
/// order is the engine's choice, and difference #8 puts PG's NULLs at the
/// opposite end from mpedb's and sqlite's.
///
/// Note what is NOT generated: `SELECT DISTINCT c ... ORDER BY pk`. It would
/// satisfy the NULL rule, but mpedb rejects it (a sort key outside the SELECT
/// list has no meaning once duplicates collapse) where sqlite invents an
/// answer. That divergence is deliberate and pinned in `distinct.test`, not
/// something to rediscover here as a false positive.
fn gen_distinct_select(rng: &mut Xorshift) -> GenStmt {
    // The sort keys, guarded to non-NULL, plus an optional random predicate —
    // built as conjuncts rather than by splicing strings, so the guard is
    // always present and always spelled `<key> IS NOT NULL` for the pin below
    // to find.
    let build = |rng: &mut Xorshift, keys: &[&str]| -> String {
        let mut conj: Vec<String> = keys.iter().map(|k| format!("{k} IS NOT NULL")).collect();
        if rng.chance(1, 2) {
            conj.push(format!("({})", gen_pred(rng)));
        }
        format!(" WHERE {}", conj.join(" AND "))
    };
    let limit = |rng: &mut Xorshift| {
        if rng.chance(1, 4) {
            format!(" LIMIT {}", rng.below(8))
        } else {
            String::new()
        }
    };
    match rng.below(4) {
        0 => {
            let w = build(rng, &["a"]);
            GenStmt {
                sql: format!("SELECT DISTINCT a FROM t{w} ORDER BY a{}", limit(rng)),
                is_select: true,
                shape: vec![Kind::Int],
            }
        }
        1 => {
            let w = build(rng, &["c"]);
            GenStmt {
                sql: format!("SELECT DISTINCT c FROM t{w} ORDER BY c{}", limit(rng)),
                is_select: true,
                shape: vec![Kind::Text],
            }
        }
        // A distinct TUPLE, ordered by both members so ties cannot make the
        // order engine-dependent.
        2 => {
            let w = build(rng, &["a", "c"]);
            GenStmt {
                sql: format!("SELECT DISTINCT a, c FROM t{w} ORDER BY a, c{}", limit(rng)),
                is_select: true,
                shape: vec![Kind::Int, Kind::Text],
            }
        }
        // count(DISTINCT x) — one row, so there is no ordering question at
        // all, which is why this one may keep an unconstrained WHERE.
        _ => {
            let w = if rng.chance(1, 2) {
                format!(" WHERE {}", gen_pred(rng))
            } else {
                String::new()
            };
            GenStmt {
                sql: format!("SELECT count(DISTINCT a), count(DISTINCT c), count(*) FROM t{w}"),
                is_select: true,
                shape: vec![Kind::Int, Kind::Int, Kind::Int],
            }
        }
    }
}

/// Boolean predicate over the fixed schema. Type-correct by construction
/// (mpedb's rigid binder would reject cross-type comparisons that sqlite
/// would happily coerce). No `/`, `%` (difference #4).
fn gen_pred(rng: &mut Xorshift) -> String {
    fn simple(rng: &mut Xorshift) -> String {
        let cmp = ["=", "<>", "!=", "<", "<=", ">", ">="];
        match rng.below(12) {
            0 => format!("pk {} {}", cmp[rng.below(7) as usize], gen_pk(rng)),
            1 => format!(
                "pk >= {} AND pk < {}",
                rng.range_i64(0, 30),
                rng.range_i64(10, 48)
            ),
            2 => format!("a {} {}", cmp[rng.below(7) as usize], rng.range_i64(-100, 100)),
            3 => format!("b {} {:.2}", cmp[rng.below(7) as usize], rng.range_i64(-100, 100) as f64 * 0.25),
            4 => format!("c {} {}", cmp[rng.below(7) as usize], gen_c_nonnull(rng)),
            5 => "a IS NULL".into(),
            6 => "a IS NOT NULL".into(),
            7 => "b IS NULL".into(),
            8 => "c IS NOT NULL".into(),
            // 3VL probes: `= NULL` matches nothing in both engines.
            9 => "a = NULL".into(),
            // NULL arithmetic propagates the same way in both engines.
            10 => format!("a + {} < {}", rng.range_i64(-5, 5), rng.range_i64(-50, 50)),
            // Lowercase-only LIKE (difference #2: sqlite's LIKE is
            // ASCII-case-insensitive; single-case data makes that moot).
            _ => {
                let start = (b'a' + rng.below(26) as u8) as char;
                if rng.chance(1, 2) {
                    format!("c LIKE '{start}%'")
                } else {
                    format!("c LIKE '_{start}%'")
                }
            }
        }
    }
    match rng.below(10) {
        0..=5 => simple(rng),
        6 => format!("({}) AND ({})", simple(rng), simple(rng)),
        7 => format!("({}) OR ({})", simple(rng), simple(rng)),
        8 => format!("NOT ({})", simple(rng)),
        _ => format!(
            "({}) AND (({}) OR ({}))",
            simple(rng),
            simple(rng),
            simple(rng)
        ),
    }
}

fn gen_c_nonnull(rng: &mut Xorshift) -> String {
    loop {
        let s = gen_c(rng);
        if s != "NULL" {
            return s;
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generator_is_deterministic() {
        let a = generate_program(123, 40);
        let b = generate_program(123, 40);
        assert_eq!(a.len(), b.len());
        for (x, y) in a.iter().zip(&b) {
            assert_eq!(x.sql, y.sql);
        }
        // Ends with the full-table probe.
        assert!(a.last().unwrap().sql.starts_with("SELECT pk, a, b, c FROM t"));
    }

    #[test]
    fn generated_sql_is_single_line_and_ascii() {
        for seed in 0..20 {
            for s in generate_program(seed, 60) {
                assert!(!s.sql.contains('\n'));
                assert!(s.sql.is_ascii());
                assert!(!s.sql.contains('/') && !s.sql.contains('%') || s.sql.contains("LIKE"),
                    "division/modulo must not be generated: {}", s.sql);
            }
        }
    }

    #[test]
    fn pipe_row_parsing() {
        let r = parse_pipe_row("3|NULL|2.75|abc", &BASE_SHAPE).unwrap();
        assert_eq!(
            r,
            vec![
                Field::Int(3),
                Field::Null,
                Field::Float(2.75),
                Field::Text("abc".into())
            ]
        );
        // Empty text field is Text(""), NOT Null (difference #11).
        let r = parse_pipe_row("3|NULL|2.75|", &BASE_SHAPE).unwrap();
        assert_eq!(r[3], Field::Text(String::new()));
        assert!(parse_pipe_row("1|2", &BASE_SHAPE).is_err());
        assert!(parse_pipe_row("x|1|1.0|a", &BASE_SHAPE).is_err());
    }

    /// The aggregate probes must actually be generated, and must actually
    /// exercise GROUP BY and HAVING. Without this the ORDER BY pin above and
    /// the three-way aggregate coverage could both go hollow — passing
    /// because nothing was generated, which is the failure mode a coverage
    /// pin exists to catch.
    #[test]
    fn generator_covers_aggregates() {
        let (mut bare, mut grouped, mut having) = (0, 0, 0);
        for seed in 0..100 {
            for s in generate_program(seed, 60) {
                if !s.sql.contains("count(") && !s.sql.contains("sum(") && !s.sql.contains("avg(")
                {
                    continue;
                }
                if s.sql.contains("GROUP BY") {
                    grouped += 1;
                } else {
                    bare += 1;
                }
                if s.sql.contains("HAVING") {
                    having += 1;
                }
            }
        }
        assert!(bare > 50, "too few bare aggregate probes: {bare}");
        let distinct = (0..100)
            .flat_map(|seed| generate_program(seed, 60))
            .filter(|s| s.sql.contains("DISTINCT"))
            .count();
        assert!(distinct > 50, "too few DISTINCT probes: {distinct}");
        assert!(grouped > 50, "too few GROUP BY probes: {grouped}");
        assert!(having > 10, "too few HAVING probes: {having}");
    }

    /// The top-level `AND` conjuncts of a statement's WHERE clause, ignoring
    /// anything nested in parentheses (where an OR may legitimately live).
    fn top_level_conjuncts(sql: &str) -> Vec<String> {
        let Some(w) = sql.find(" WHERE ") else {
            return Vec::new();
        };
        let rest = &sql[w + " WHERE ".len()..];
        let end = ["ORDER BY", "GROUP BY", "LIMIT"]
            .iter()
            .filter_map(|k| rest.find(k))
            .min()
            .unwrap_or(rest.len());
        let clause = &rest[..end];
        let (mut out, mut depth, mut cur) = (Vec::new(), 0i32, String::new());
        let mut it = clause.char_indices().peekable();
        while let Some((i, ch)) = it.next() {
            match ch {
                '(' => depth += 1,
                ')' => depth -= 1,
                _ => {}
            }
            if depth == 0 && clause[i..].starts_with(" AND ") {
                out.push(cur.trim().to_string());
                cur.clear();
                for _ in 0.." AND ".len() - 1 {
                    it.next();
                }
                continue;
            }
            cur.push(ch);
        }
        out.push(cur.trim().to_string());
        out
    }

    #[test]
    fn top_level_conjuncts_ignores_nested_ors() {
        assert_eq!(
            top_level_conjuncts("SELECT DISTINCT a FROM t WHERE a IS NOT NULL AND (a > 1 OR c = 'x') ORDER BY a"),
            vec!["a IS NOT NULL".to_string(), "(a > 1 OR c = 'x')".to_string()]
        );
        // An OR-ed guard is NOT a conjunct — the case the pin must not accept.
        assert_eq!(
            top_level_conjuncts("SELECT DISTINCT a FROM t WHERE a IS NOT NULL OR c = 'x' ORDER BY a"),
            vec!["a IS NOT NULL OR c = 'x'".to_string()]
        );
        assert!(top_level_conjuncts("SELECT a FROM t ORDER BY pk").is_empty());
    }

    /// Difference #8: PostgreSQL's ASC default is NULLS LAST where
    /// mpedb/sqlite put NULLS FIRST. Safe only while every generated sort key
    /// is NULL-free — either the NOT NULL `pk`, or a key the same statement
    /// has guarded with `IS NOT NULL`. Pinned here.
    #[test]
    fn generator_only_orders_by_non_null() {
        for seed in 0..100 {
            for s in generate_program(seed, 60) {
                let mut rest = s.sql.as_str();
                while let Some(pos) = rest.find("ORDER BY") {
                    rest = &rest[pos + "ORDER BY".len()..];
                    // `pk` is NOT NULL by schema. Any other sort key must be
                    // guarded to non-NULL by the same statement — the rule is
                    // "never sort by something that can be NULL" (difference
                    // #8), not "only ever sort by pk"; grouped aggregate
                    // probes sort by their key, which the WHERE has already
                    // made NULL-free.
                    let sorts_by_pk = rest.starts_with(" pk");
                    let key = rest.trim_start().split([' ', ',']).next().unwrap_or("");
                    // The guard must be a TOP-LEVEL conjunct of the WHERE. A
                    // substring search would also accept `WHERE a IS NOT NULL
                    // OR …`, which guarantees nothing — the whole point of the
                    // pin is that it cannot be satisfied by accident.
                    let guarded = !key.is_empty()
                        && top_level_conjuncts(&s.sql)
                            .iter()
                            .any(|c| *c == format!("{key} IS NOT NULL"));
                    assert!(
                        sorts_by_pk || guarded,
                        "ORDER BY on a nullable column would hit the \
                         PG NULLS-placement difference: {}",
                        s.sql
                    );
                }
            }
        }
    }

    /// Difference #11: the corpus must actually exercise empty-string
    /// text — both as a stored value and as a predicate comparand.
    #[test]
    fn generator_covers_empty_string() {
        let mut in_insert = false;
        let mut in_pred = false;
        for seed in 0..100 {
            for s in generate_program(seed, 60) {
                if s.sql.starts_with("INSERT") && s.sql.contains("''") {
                    in_insert = true;
                }
                if s.sql.contains("c = ''") || s.sql.contains("c <> ''") {
                    in_pred = true;
                }
            }
        }
        assert!(in_insert, "no empty-string INSERT generated");
        assert!(in_pred, "no empty-string predicate generated");
    }

    #[test]
    fn one_program_agrees() {
        // Smoke test: a single fixed-seed program through the whole pipeline.
        let stats = run_differential(999, 1, 30).unwrap();
        assert_eq!(stats.programs, 1);
        assert_eq!(stats.statements, 30);
        assert!(stats.selects_compared >= 1);
    }
}
